version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: employee-profile-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    restart: always

volumes:
  db:
    driver: local